# Adds a "Sponsor" button to the repo. Uncomment and fill in the handles you use.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [Abdo-ka]
# ko_fi: your_handle
# buy_me_a_coffee: your_handle
# custom: ["https://example.com/donate"]
